services:
  postgres:
    image: postgres:16
    container_name: qms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: qms_platform
      POSTGRES_USER: qms_user
      POSTGRES_PASSWORD: qmapass123
    ports:
      - "5432:5432"
    volumes:
      - qms_postgres_data:/var/lib/postgresql/data

volumes:
  qms_postgres_data: