"""add external file url to document revisions

Revision ID: 906b503de67a
Revises: fc90967728c7
Create Date: 2026-05-01 15:46:00.193216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906b503de67a'
down_revision: Union[str, Sequence[str], None] = 'fc90967728c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_revisions', sa.Column('external_file_url', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('document_revisions', 'external_file_url')
    # ### end Alembic commands ###
